// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://phruepuejsyritaxvcnl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBocnVlcHVlanN5cml0YXh2Y25sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0OTQ3NTEsImV4cCI6MjA2ODA3MDc1MX0.fVfQKG-neIoVxssfJVLdfVXn26GIQTXVIV3vc6DFnNs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});